
server:
  port: 8080
  servlet:
    context-path: /l-life


spring:
  datasource:
    url: ${db-url}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${db-username}
    password: ${db-password}
#  profiles:
#    include:
#      - dev

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false
      prefix: classpath:/templates/

mybatis:
  type-aliases-package: kosa.com.suntofu.L_Life.*.vo
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    kosa.com.suntofu: debug
