server:
  port: 8080
  servlet:
    context-path: /l-life
  tomcat: #  tomcat 메트릭 설정 on. 톰캣 메트릭은 tomcat. 으로 시작
    mbeanregistry: # 톰캣 메트릭을 모두 사용하려면 다음 옵션을 켜야하며, 옵션을 켜지 않으면 tomcat.session. 관련정보만 노출됩니다
      enabled: true
  ssl:
    enabled: false
#    enabled: true
#    key-store: classpath:ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ${key-store-password}

spring:
  security:
    user:
      name: l-life
      password: 1234
  profiles:
    include: config
  datasource:
    url: ${db-url}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ${db-username}
    password: ${db-password}
  kafka:
    consumer:
      bootstrap-servers: livart-life.com:9093
    producer:
      bootstrap-servers: livart-life.com:9093
  data:
    mongodb:
      host: mongodb.livart-life.com
      port: 27017
      username: llife
      password: kosa1234

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false
      prefix: classpath:/templates/

  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: true
      host: redis.livart-life.com
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${smtp-username}
    password: ${smtp-password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  redis:
    host: redis.livart-life.com
    password: ${redis-password}
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: '/secure/actuator'

mybatis:
  type-aliases-package: kosa.com.suntofu.L_LIFE.*.vo
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    kosa.com.suntofu: debug
    sql: off
    jdbc: off
    jdbc.sqlonly: debug

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: false

cloud:
  aws:
    s3:
      bucket: img-resource
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${aws-access-key}
      secretKey: ${aws-secret-key}
      instanceProfile: true

